name: ServiceNow Pull Request Pipeline
'on':
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Run ATF on dev instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: ServiceNow CI/CD Apply Changes
        uses: ServiceNow/sncicd-apply-changes@1.2.1
        env:
          snowSSHPrivateKey: '${{ secrets.SSH_PRIVATE_KEY }}'
          snowSSHPublicKey: '${{ secrets.SSH_PUBLIC_KEY }}'
          snowSSHHost: '${{ secrets.SSH_HOST }}'
          snowSourceInstance: '${{ secrets.NOW_DEV_INSTANCE }}'
          appSysID: '${{ secrets.APP_SYS_ID }}'
      - name: Run Tests
        id: atf_test_dev
        uses: ServiceNow/sncicd-tests-run@1.0.0
        with:
          browserName: null
          browserVersion: null
          osName: null
          osVersion: null
          testSuiteSysId: '${{ secrets.TEST_SUITE_ID }}'
          testSuiteName: null
        env:
          snowSSHPrivateKey: '${{ secrets.SSH_PRIVATE_KEY }}'
          snowSSHPublicKey: '${{ secrets.SSH_PUBLIC_KEY }}'
          snowSSHHost: '${{ secrets.SSH_HOST }}'
          snowInstallInstance: '${{ secrets.NOW_DEV_INSTANCE }}'
